# SPDX-FileCopyrightText: 2024 Telef贸nica Innovaci贸n Digital and contributors
# SPDX-License-Identifier: Apache-2.0

name: 'Check License Compliance'
description: 'GitHub Action to check that dependencies are compliant with approved licenses'
author: 'Telef贸nica Innovaci贸n Digital'

inputs:
  log:
    description: 'Log level'
    type: choice
    options:
      - 'silly'
      - 'debug'
      - 'verbose'
      - 'info'
      - 'warn'
      - 'error'
      - 'silent'
    required: false
  reporter:
    description: 'Reporter to use'
    type: choice
    options:
      - 'json'
      - 'markdown'
      - 'text'
    default: 'text'
    required: false
  fail-on-not-valid:
    description: 'Fail the action (exit code 1) when the result is not valid'
    type: boolean
    default: 'true'
  config:
    description: 'Configuration object expressed as a JSON string'
    multiline: true
    required: false
  config-file:
    description: 'Path to a configuration file'
    default: 'check-license-compliance.config.yml'
outputs:
  found-forbidden:
    description: 'Whether forbidden licenses were found'
  found-warning:
    description: 'Whether dangerous licenses were found'
  valid:
    description: 'Whether the check is valid or not'
  report:
    description: 'A report containing the results of the check'
runs:
  using: docker
  image: Dockerfile
