# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

services:
  action:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check-license-compliance
    volumes:
      # Mount the current directory as /github/workspace, like the GitHub Actions runner does
      - ./:/github/workspace
    env_file: .env
