# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - release

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: ${{ secrets.NPM_TOKEN_XCUT }}

      - name: Build dist/ Directory
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Check spelling
        run: pnpm cspell

      - name: Check TypeScript types
        run: pnpm check:types
      
      - name: Test unit
        run: pnpm test:unit

      - name: Upload coverage
        id: upload-coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      # This will fail the workflow if the `src/lib/proto` directory is different than expected, meaning that protobuf files were not compiled.
      - name: Compare Directories
        id: diff
        run: |
          if [ ! -d src/lib/proto/ ]; then
            echo "Expected src/lib/proto directory does not exist.  See status below:"
            ls -la src/lib
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text src/lib/proto/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text src/lib/proto/
            exit 1
          fi

      # If `dist/` was different than expected, upload the expected version as a
      # workflow artifact.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  check-spdx-headers:
    name: Check SPDX Headers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check SPDX headers
        uses: Telefonica/check-spdx-headers/.github/actions/check-and-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
